/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.validation;

import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class CommandsValidator extends AbstractCommandsValidator {
  @Check
  public void specializationLengthMatchesParent(final /* AlphaCommandSpecialization */Object specialization) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field ModelPackage is undefined"
      + "\narguments cannot be resolved"
      + "\nlength cannot be resolved"
      + "\n!= cannot be resolved"
      + "\ncommand cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\narguments cannot be resolved"
      + "\nlength cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nALPHA_COMMAND_SPECIALIZATION__ARGUMENTS cannot be resolved");
  }
}
