variables:
  # shell environment variable to specify timezone
  TZ: "UTC-2"

  # Maven options
  # use '/cache/.m2/repository" as local maven repository.
  # '/cache' is automatically added as volume for docker executors
  # to use another cachedir it need to be added to the docker
  # executor's 'volumes' parameter (in config.toml)
  MAVEN_OPTS: "-Dmaven.repo.local=/cache/.m2/repository -Xmx3072m"

  # Uncomment to enable debug traces
  # !!! WARNING !!! 
  #     This will expose secret variables !
  #CI_DEBUG_TRACE: "true"

  # Update site artifacts storage dir
  # gitlab pages expects there to be a public/ directory
  UPDATESITE_ARTIFACTS_DIR: "public"

# default docker image. can be overriden per job.
image: maven:3-jdk-11

pages:
  script:
    - mvn -B -e -fae clean package
    - mkdir -p $UPDATESITE_ARTIFACTS_DIR
    - mv releng/alpha.language.update/target/repository $UPDATESITE_ARTIFACTS_DIR/update-site
    - echo 
  artifacts:
    paths:
      # files to be exposed at the Page URL
      - $UPDATESITE_ARTIFACTS_DIR
  rules:
    # This ensures that only pushes to the default branch will trigger
    # a pages deploy
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
