affine matmult_aabft { N | -1 + N >= 0  }
	input
		float A { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
		float B { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
	output
		float C { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
		float check_C_i_inv { i |  i >= 0  &&  -1 + N - i >= 0  &&  -1 + N >= 0  };
		float check_C_j_inv { j |  j >= 0  &&  -1 + N - j >= 0  &&  -1 + N >= 0  };
	local
		float check_C_i_0 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_C_i_1 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_C_j_0 { j |  j >= 0  &&  -1 + N - j >= 0  };
		float check_C_j_1 { j |  j >= 0  &&  -1 + N - j >= 0  };
	let
		C = reduce(+, (i,j,k->i,j), ((i,j,k->i,k)@(A) * (i,j,k->k,j)@(B)));
		
		check_C_i_0 = reduce(+, (i,j->i), (i,j->i,j)@(C));
		
		check_C_i_1 = reduce(+, (i,j->i), (i,j->i,j)@({ i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  } : reduce(+, (i,j,k->i,j), ((i,j,k->i,k)@(A) * (i,j,k->k,j)@(B)))));
		
		check_C_i_inv = ((check_C_i_0 - check_C_i_1) / check_C_i_0);
		
		check_C_j_0 = reduce(+, (i,j->j), (i,j->i,j)@(C));
		
		check_C_j_1 = reduce(+, (i,j->j), (i,j->i,j)@({ i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  } : reduce(+, (i,j,k->i,j), ((i,j,k->i,k)@(A) * (i,j,k->k,j)@(B)))));
		
		check_C_j_inv = ((check_C_j_0 - check_C_j_1) / check_C_j_0);
.
