affine fsub { N | -1 + N >= 0  }
	input
		float L { i,j |  -1 + N - i >= 0  &&  j >= 0  &&  i - j >= 0  };
		float b { j |  j >= 0  &&  -1 + N - j >= 0  };
	output
		float x { i |  i >= 0  &&  -1 + N - i >= 0  };
	let
		x = case 
			{ i |  i == 0  &&  -1 + N >= 0  } : ((i->i)@(b) / (i->i,i)@(L));
			{ i |  -1 + N >= 0  &&  -1 + i >= 0  } : (((i->i)@(b) - reduce(+, (i,j->i), { i,j |  -1 + N >= 0  &&  j >= 0  &&  -1 + i - j >= 0  } : ((i,j->i,j)@(L) * (i,j->j)@(x)))) / (i->i,i)@(L));
		esac;
.
