/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.scoping;

import com.google.inject.Inject;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class CommandsScopeProvider extends AbstractCommandsScopeProvider {
  @Inject
  private IQualifiedNameProvider nameProvider;

  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    throw new Error("Unresolved compilation problems:"
      + "\nCommandBinding cannot be resolved to a type."
      + "\nArgumentBinding cannot be resolved to a type."
      + "\nCommandBinding cannot be resolved to a type."
      + "\nArgumentBinding cannot be resolved to a type."
      + "\nAlphaCommand cannot be resolved to a type."
      + "\nArgumentRenaming cannot be resolved to a type."
      + "\nCommandBinding cannot be resolved to a type."
      + "\nArgumentRenaming cannot be resolved to a type."
      + "\nAlphaCommand cannot be resolved to a type."
      + "\nThe method or field ModelPackage is undefined"
      + "\nThe method or field AlphaCommand is undefined"
      + "\nThe method or field ModelPackage is undefined"
      + "\nThe method or field ModelPackage is undefined"
      + "\nThe method or field ModelPackage is undefined"
      + "\nThe method or field ModelPackage is undefined"
      + "\nLiterals cannot be resolved"
      + "\nCOMMAND_BINDING__BIND_TARGET_COMMAND cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nARGUMENT_BINDING__BIND_TARGET cannot be resolved"
      + "\nbindTargetCommand cannot be resolved"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\n!== cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\narguments cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nARGUMENT_BINDING__BIND_SOURCE cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\narguments cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nARGUMENT_RENAMING__BIND_TARGET cannot be resolved"
      + "\nbindTargetCommand cannot be resolved"
      + "\n!== cannot be resolved"
      + "\n&& cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\n!== cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\narguments cannot be resolved"
      + "\nLiterals cannot be resolved"
      + "\nARGUMENT_RENAMING__BIND_SOURCE cannot be resolved"
      + "\nsignature cannot be resolved"
      + "\narguments cannot be resolved");
  }
}
