affine lud_aabft { N | -1 + N >= 0  }
	input
		float A { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
	output
		float L { i,j |  -1 + N - i >= 0  &&  j >= 0  &&  i - j >= 0  };
		float U { i,j |  i >= 0  &&  -i + j >= 0  &&  -1 + N - j >= 0  };
		float check_U_i_inv { i |  i >= 0  &&  -1 + N - i >= 0  &&  -1 + N >= 0  };
		float check_U_j_inv { j |  j >= 0  &&  -1 + N - j >= 0  &&  -1 + N >= 0  };
		float check_L_i_inv { i |  i >= 0  &&  -1 + N - i >= 0  &&  -1 + N >= 0  };
		float check_L_j_inv { j |  j >= 0  &&  -1 + N - j >= 0  &&  -1 + N >= 0  };
	local
		float check_U_i_0 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_U_i_1 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_U_j_0 { j |  j >= 0  &&  -1 + N - j >= 0  };
		float check_U_j_1 { j |  j >= 0  &&  -1 + N - j >= 0  };
		float check_L_i_0 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_L_i_1 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_L_j_0 { j |  j >= 0  &&  -1 + N - j >= 0  };
		float check_L_j_1 { j |  j >= 0  &&  -1 + N - j >= 0  };
	let
		U = case 
			{ i,j |  i == 0  &&  -1 + N >= 0  } : (i,j->i,j)@(A);
			{ i,j |  -1 + N >= 0  &&  -1 + i >= 0  &&  -i + j >= 0  } : ((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + i - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U))));
		esac;
		
		L = case 
			{ i,j |  j == 0  &&  -1 + N >= 0  } : ((i,j->i,j)@(A) / (i,j->j,j)@(U));
			{ i,j |  -1 + N >= 0  &&  -1 + j >= 0  } : (((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + j - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U)))) / (i,j->j,j)@(U));
		esac;
		
		check_U_i_0 = reduce(+, (i,j->i), (i,j->i,j)@(U));
		
		check_U_i_1 = reduce(+, (i,j->i), (i,j->i,j)@({ i,j |  i >= 0  &&  -i + j >= 0  &&  -1 + N - j >= 0  } : case 
			{ i,j |  i == 0  &&  -1 + N >= 0  } : (i,j->i,j)@(A);
			{ i,j |  -1 + N >= 0  &&  -1 + i >= 0  &&  -i + j >= 0  } : ((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + i - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U))));
		esac));
		
		check_U_i_inv = ((check_U_i_0 - check_U_i_1) / check_U_i_0);
		
		check_U_j_0 = reduce(+, (i,j->j), (i,j->i,j)@(U));
		
		check_U_j_1 = reduce(+, (i,j->j), (i,j->i,j)@({ i,j |  i >= 0  &&  -i + j >= 0  &&  -1 + N - j >= 0  } : case 
			{ i,j |  i == 0  &&  -1 + N >= 0  } : (i,j->i,j)@(A);
			{ i,j |  -1 + N >= 0  &&  -1 + i >= 0  &&  -i + j >= 0  } : ((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + i - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U))));
		esac));
		
		check_U_j_inv = ((check_U_j_0 - check_U_j_1) / check_U_j_0);
		
		check_L_i_0 = reduce(+, (i,j->i), (i,j->i,j)@(L));
		
		check_L_i_1 = reduce(+, (i,j->i), (i,j->i,j)@({ i,j |  -1 + N - i >= 0  &&  j >= 0  &&  i - j >= 0  } : case 
			{ i,j |  j == 0  &&  -1 + N >= 0  } : ((i,j->i,j)@(A) / (i,j->j,j)@(U));
			{ i,j |  -1 + N >= 0  &&  -1 + j >= 0  } : (((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + j - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U)))) / (i,j->j,j)@(U));
		esac));
		
		check_L_i_inv = ((check_L_i_0 - check_L_i_1) / check_L_i_0);
		
		check_L_j_0 = reduce(+, (i,j->j), (i,j->i,j)@(L));
		
		check_L_j_1 = reduce(+, (i,j->j), (i,j->i,j)@({ i,j |  -1 + N - i >= 0  &&  j >= 0  &&  i - j >= 0  } : case 
			{ i,j |  j == 0  &&  -1 + N >= 0  } : ((i,j->i,j)@(A) / (i,j->j,j)@(U));
			{ i,j |  -1 + N >= 0  &&  -1 + j >= 0  } : (((i,j->i,j)@(A) - reduce(+, (i,j,k->i,j), { i,j,k |  -1 + N >= 0  &&  k >= 0  &&  -1 + j - k >= 0  } : ((i,j,k->i,k)@(L) * (i,j,k->k,j)@(U)))) / (i,j->j,j)@(U));
		esac));
		
		check_L_j_inv = ((check_L_j_0 - check_L_j_1) / check_L_j_0);
.
