affine scalmat_aabft { N | -1 + N >= 0  }
	input
		float k {|};
		float A { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
	output
		float B { i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  };
		float check_B_i_inv { i |  i >= 0  &&  -1 + N - i >= 0  &&  -1 + N >= 0  };
		float check_B_j_inv { j |  j >= 0  &&  -1 + N - j >= 0  &&  -1 + N >= 0  };
	local
		float check_B_i_0 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_B_i_1 { i |  i >= 0  &&  -1 + N - i >= 0  };
		float check_B_j_0 { j |  j >= 0  &&  -1 + N - j >= 0  };
		float check_B_j_1 { j |  j >= 0  &&  -1 + N - j >= 0  };
	let
		B = ((i,j->)@(k) * (i,j->i,j)@(A));
		
		check_B_i_0 = reduce(+, (i,j->i), (i,j->i,j)@(B));
		
		check_B_i_1 = reduce(+, (i,j->i), (i,j->i,j)@({ i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  } : ((i,j->)@(k) * (i,j->i,j)@(A))));
		
		check_B_i_inv = ((check_B_i_0 - check_B_i_1) / check_B_i_0);
		
		check_B_j_0 = reduce(+, (i,j->j), (i,j->i,j)@(B));
		
		check_B_j_1 = reduce(+, (i,j->j), (i,j->i,j)@({ i,j |  i >= 0  &&  -1 + N - i >= 0  &&  j >= 0  &&  -1 + N - j >= 0  } : ((i,j->)@(k) * (i,j->i,j)@(A))));
		
		check_B_j_inv = ((check_B_j_0 - check_B_j_1) / check_B_j_0);
.
