package alpha.abft.codegen;

import alpha.abft.ABFT;
import alpha.abft.codegen.util.ISLASTNodeVisitor;
import alpha.abft.codegen.util.MemoryMap;
import alpha.model.AlphaSystem;
import alpha.model.Variable;
import alpha.model.util.ISLUtil;
import com.google.common.base.Objects;
import com.google.common.collect.Iterables;
import fr.irisa.cairn.jnimap.isl.ISLASTBuild;
import fr.irisa.cairn.jnimap.isl.ISLASTNode;
import fr.irisa.cairn.jnimap.isl.ISLIdentifierList;
import fr.irisa.cairn.jnimap.isl.ISLSchedule;
import fr.irisa.cairn.jnimap.isl.ISLSet;
import java.util.Collections;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Conversions;
import org.eclipse.xtext.xbase.lib.ExclusiveRange;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.Pair;

@SuppressWarnings("all")
public class WrapperCodeGen extends SystemCodeGen {
  private final AlphaSystem v1System;

  private final AlphaSystem v2System;

  public static String generateWrapper(final AlphaSystem baselineSystem, final AlphaSystem v1System, final AlphaSystem v2System, final MemoryMap memoryMap, final Version version, final int[] tileSizes) {
    String _xblockexpression = null;
    {
      final WrapperCodeGen generator = new WrapperCodeGen(baselineSystem, v1System, v2System, memoryMap, version, tileSizes);
      _xblockexpression = generator.generate();
    }
    return _xblockexpression;
  }

  public WrapperCodeGen(final AlphaSystem system, final AlphaSystem v1System, final AlphaSystem v2System, final MemoryMap memoryMap, final Version version, final int[] tileSizes) {
    super(system, memoryMap, version, tileSizes);
    this.v1System = v1System;
    this.v2System = v2System;
  }

  @Override
  public String generate() {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("// ");
    String _name = this.getSystem().getName();
    _builder.append(_name);
    _builder.append("-wrapper.c");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("#include<stdio.h>");
    _builder.newLine();
    _builder.append("#include<stdlib.h>");
    _builder.newLine();
    _builder.append("#include<math.h>");
    _builder.newLine();
    _builder.append("#include<string.h>");
    _builder.newLine();
    _builder.append("#include<sys/time.h>");
    _builder.newLine();
    _builder.newLine();
    _builder.append("#define max(x, y)   ((x)>(y) ? (x) : (y))");
    _builder.newLine();
    _builder.append("#define min(x, y)   ((x)>(y) ? (y) : (x))");
    _builder.newLine();
    _builder.append("#define ceild(n,d)  (int)ceil(((double)(n))/((double)(d)))");
    _builder.newLine();
    _builder.append("#define floord(n,d) (int)floor(((double)(n))/((double)(d)))");
    _builder.newLine();
    _builder.append("#define mallocCheck(v,s,d) if ((v) == NULL) { printf(\"Failed to allocate memory for %s : size=%lu\\n\", \"sizeof(d)*(s)\", sizeof(d)*(s)); exit(-1); }");
    _builder.newLine();
    _builder.append("#define new_result() { .valid=0, .TP=0L, .FP=0L, .TN=0L, .FN=0L, .TPR=0.0f, .FPR=0.0f, .FNR=0.0f, .bit=0, .inj={.t=0, .i=0, .j=0, .k=0}, .result=0.0f, .noise=0.0f}");
    _builder.newLine();
    _builder.append("#define new_result_summary() { .TP=0L, .FP=0L, .TN=0L, .FN=0L, .TPR=0.0f, .FPR=0.0f, .FNR=0.0f, .bit=0, .nb_detected=0L, .nb_results=0L, .result=0.0f, .noise=0.0f}");
    _builder.newLine();
    _builder.newLine();
    _builder.append("// External system declarations");
    _builder.newLine();
    CharSequence _signature = this.signature(this.getSystem(), Version.BASELINE);
    _builder.append(_signature);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    CharSequence _signature_1 = this.signature(this.v1System);
    _builder.append(_signature_1);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    CharSequence _signature_2 = this.signature(this.v2System);
    _builder.append(_signature_2);
    _builder.append(";");
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("struct INJ {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int t;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int i;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int j;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int k;");
    _builder.newLine();
    _builder.append("};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("struct Result {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int valid;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long TP;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long FP;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long TN;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long FN;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float TPR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FPR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FNR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int bit;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("struct INJ inj;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("double result;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("double noise;");
    _builder.newLine();
    _builder.append("};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("struct ResultsSummary {");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float TP;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FP;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float TN;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FN;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float TPR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FPR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("float FNR;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("int bit;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long nb_detected;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("long nb_results;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("double result;");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("double noise;");
    _builder.newLine();
    _builder.append("};");
    _builder.newLine();
    _builder.newLine();
    _builder.append("// Memory mapped targets");
    _builder.newLine();
    final Function1<Variable, Boolean> _function = (Variable it) -> {
      return it.isLocal();
    };
    final Function1<Variable, Pair<String, ISLSet>> _function_1 = (Variable it) -> {
      String _name_1 = this.getMemoryMap().getName(it.getName());
      ISLSet _domain = it.getDomain();
      return Pair.<String, ISLSet>of(_name_1, _domain);
    };
    final Function1<Pair<String, ISLSet>, String> _function_2 = (Pair<String, ISLSet> it) -> {
      return this.memoryTargetMacro(it);
    };
    String _join = IterableExtensions.join(IterableExtensions.<Pair<String, ISLSet>, String>map(IterableExtensions.<Variable, Pair<String, ISLSet>>map(IterableExtensions.<Variable>reject(this.getSystem().getVariables(), _function), _function_1), _function_2), "\n");
    _builder.append(_join);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    _builder.append("// Memory access functions");
    _builder.newLine();
    final Function1<Variable, Boolean> _function_3 = (Variable it) -> {
      return it.isLocal();
    };
    final Function1<Variable, CharSequence> _function_4 = (Variable it) -> {
      return this.memoryMacro(it);
    };
    String _join_1 = IterableExtensions.join(IterableExtensions.<Variable, CharSequence>map(IterableExtensions.<Variable>reject(this.getSystem().getVariables(), _function_3), _function_4), "\n");
    _builder.append(_join_1);
    _builder.newLineIfNotEmpty();
    _builder.newLine();
    String _mainFunction = this.mainFunction(this.getSystem());
    _builder.append(_mainFunction);
    _builder.newLineIfNotEmpty();
    return _builder.toString();
  }

  public String mainFunction(final AlphaSystem system) {
    String _xblockexpression = null;
    {
      final List<String> paramNames = system.getParameterDomain().getParamNames();
      final Function1<String, String> _function = (String P) -> {
        String _xblockexpression_1 = null;
        {
          final int i = paramNames.indexOf(P);
          StringConcatenation _builder = new StringConcatenation();
          _builder.append("long ");
          _builder.append(P);
          _builder.append(" = atol(argv[");
          _builder.append((i + 1));
          _builder.append("])");
          _xblockexpression_1 = _builder.toString();
        }
        return _xblockexpression_1;
      };
      final List<String> paramInits = ListExtensions.<String, String>map(paramNames, _function);
      final int sDims = this.getStencilVar().getDomain().getIndexNames().size();
      final Function1<Integer, String> _function_1 = (Integer it) -> {
        return "%*d";
      };
      final String indexNameStr = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_1), ",");
      final Function1<Integer, String> _function_2 = (Integer i) -> {
        String _get = this.getStencilVar().getDomain().getIndexNames().get((i).intValue());
        return ("sBox, r.inj." + _get);
      };
      final String injStr = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_2), ", ");
      final Function1<Integer, String> _function_3 = (Integer it) -> {
        return "%*s";
      };
      final String indexNameHeaderStr = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_3), ",");
      final Function1<Integer, String> _function_4 = (Integer i) -> {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("sBox, \"inj.");
        String _get = this.getStencilVar().getDomain().getIndexNames().get((i).intValue());
        _builder.append(_get);
        _builder.append("\"");
        return _builder.toString();
      };
      final String injHeaderStr = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_4), ", ");
      final Function1<Integer, String> _function_5 = (Integer i) -> {
        StringConcatenation _builder = new StringConcatenation();
        _builder.append("sBox, \"-\"");
        return _builder.toString();
      };
      final String injSummaryStr = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_5), ", ");
      final int TT = this.getTileSizes()[0];
      int _size = ((List<Integer>)Conversions.doWrapArray(this.getTileSizes())).size();
      final Function1<Integer, Integer> _function_6 = (Integer i) -> {
        return Integer.valueOf(this.getTileSizes()[(i).intValue()]);
      };
      final Integer TS = IterableExtensions.<Integer>max(IterableExtensions.<Integer, Integer>map(new ExclusiveRange(1, _size, true), _function_6));
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("#ifdef ");
      _builder.append(SystemCodeGen.ERROR_INJECTION);
      _builder.newLineIfNotEmpty();
      _builder.append("static int tBox;");
      _builder.newLine();
      _builder.append("static int sBox;");
      _builder.newLine();
      _builder.append("static int rBox;");
      _builder.newLine();
      _builder.append("static int runBox;");
      _builder.newLine();
      _builder.append("static char eol[2];");
      _builder.newLine();
      _builder.append("static int run;");
      _builder.newLine();
      _builder.append("static int R;");
      _builder.newLine();
      _builder.append("static int log_flag;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("void printHeader() {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("int S = 300;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("char header_str[S];");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sprintf(header_str, \"   %*s : (%*s,");
      _builder.append(indexNameHeaderStr, "\t");
      _builder.append(") : (%*s,%*s,%*s,%*s) : %*s, %*s\", 4, \"bit\", tBox, \"inj.t\", ");
      _builder.append(injHeaderStr, "\t");
      _builder.append(", rBox, \"TP\", rBox, \"FP\", rBox, \"TN\", rBox, \"FN\", 12, \"Detected (%)\", 8, \"FPR (%)\");");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("char header_bar[S]; for (int i=0; i<S; i++) header_bar[i] = \'-\';");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("fprintf(stdout, \"%.*s\\n\", (int)strlen(header_str), header_bar);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("fprintf(stdout, \"%s\\n\", header_str);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("fprintf(stdout, \"%.*s\\n\", (int)strlen(header_str), header_bar);");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("void print(int version, struct Result r) {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("if (!log_flag) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("return;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("int detected = r.TP > 0 ? 1 : 0;");
      _builder.newLine();
      _builder.append("    ");
      _builder.append("printf(\"v%d,%*d : (%*d,");
      _builder.append(indexNameStr, "    ");
      _builder.append(") : (%*ld,%*ld,%*ld,%*ld) : %*d, %*.2f (%*d/%d runs)%s\", version, 4, r.bit, tBox, r.inj.t, ");
      _builder.append(injStr, "    ");
      _builder.append(", rBox, r.TP, rBox, r.FP, rBox, r.TN, rBox, r.FN, 12, detected, 8, r.FPR, runBox, run, R, eol);");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      _builder.append("fflush(stdout);");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("void accumulate_result(struct ResultsSummary *acc, struct Result r) {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->TP += r.TP;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->FP += r.FP;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->TN += r.TN;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->FN += r.FN;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->TPR += r.TPR;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->FPR += r.FPR;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->FNR += r.FNR;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->bit = r.bit;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("if (r.TP > 0) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("acc->nb_detected++;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("acc->nb_results++;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("void print_summary(int version, struct ResultsSummary *s) {");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->TP = s->TP / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->FP = s->FP / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->TN = s->TN / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->FN = s->FN / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->TPR = s->TPR / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->FPR = s->FPR / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("s->FNR = s->FNR / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("float detected_rate =100 * s->nb_detected / s->nb_results;");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("printf(\"v%d,%*d : (%*s,");
      _builder.append(indexNameHeaderStr, "\t");
      _builder.append(") : (%*.2f,%*.2f,%*.2f,%*.2f) : %*.2f, %*.2f (%*d/%d runs)\\n\", version, 4, s->bit, tBox, \"-\", ");
      _builder.append(injSummaryStr, "\t");
      _builder.append(", rBox, s->TP, rBox, s->FP, rBox, s->TN, rBox, s->FN, 12, detected_rate, 8, s->FPR, runBox, run, R);");
      _builder.newLineIfNotEmpty();
      _builder.append("}");
      _builder.newLine();
      _builder.append("#endif");
      _builder.newLine();
      _builder.newLine();
      _builder.append("int main(int argc, char **argv) ");
      _builder.newLine();
      _builder.append("{");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("if (argc < ");
      int _size_1 = paramNames.size();
      int _plus = (_size_1 + 1);
      _builder.append(_plus, "\t");
      _builder.append(") {");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("printf(\"usage: %s ");
      String _join = IterableExtensions.join(paramNames, " ");
      _builder.append(_join, "\t\t");
      _builder.append("\\n\", argv[0]);");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("return 1;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// Parse parameter sizes");
      _builder.newLine();
      _builder.append("\t");
      String _join_1 = IterableExtensions.join(paramInits, ";\n");
      _builder.append(_join_1, "\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      String _localMemoryAllocation = this.localMemoryAllocation();
      _builder.append(_localMemoryAllocation, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#ifdef ");
      _builder.append(SystemCodeGen.NOISE, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("srand(time(NULL));");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#else");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("srand(0);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#endif");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      final Function1<Variable, String> _function_7 = (Variable it) -> {
        return this.inputInitialization(it);
      };
      String _join_2 = IterableExtensions.join(ListExtensions.<Variable, String>map(system.getInputs(), _function_7), "\n");
      _builder.append(_join_2, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      final Function1<Variable, String> _function_8 = (Variable it) -> {
        return this.inputInitialization(it);
      };
      String _join_3 = IterableExtensions.join(ListExtensions.<Variable, String>map(system.getOutputs(), _function_8), "\n");
      _builder.append(_join_3, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#if defined ");
      _builder.append(SystemCodeGen.TIMING, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("struct Result r0 = ");
      CharSequence _call = this.call(system);
      _builder.append(_call, "\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("struct Result r1 = ");
      CharSequence _call_1 = this.call(this.v1System);
      _builder.append(_call_1, "\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("struct Result r2 = ");
      CharSequence _call_2 = this.call(this.v2System);
      _builder.append(_call_2, "\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("printf(\"v0:%0.4f\\n\", r0.result);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("printf(\"v1:%0.4f\\n\", r1.result);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("printf(\"v2:%0.4f\\n\", r2.result);");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#elif defined ");
      _builder.append(SystemCodeGen.ERROR_INJECTION, "\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("tBox = max((int)log10(T) + 1, 6);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sBox = max((int)log10(N) + 1, 6);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("rBox = (int)log10(2*(T/(float)");
      int _get = this.getTileSizes()[0];
      _builder.append(_get, "\t");
      _builder.append(")*");
      final Function1<Integer, String> _function_9 = (Integer i) -> {
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("(N/(float)");
        int _get_1 = this.getTileSizes()[(i).intValue()];
        _builder_1.append(_get_1);
        _builder_1.append(")");
        return _builder_1.toString();
      };
      String _join_4 = IterableExtensions.join(IterableExtensions.<Integer, String>map(new ExclusiveRange(1, sDims, true), _function_9), "*");
      _builder.append(_join_4, "\t");
      _builder.append(") + 4;");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.append("if (getenv(\"VERBOSE\") != NULL) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("strcpy(eol, \"\\n\");");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("} else {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("strcpy(eol, \"\\r\");");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("log_flag = (getenv(\"LOG\") == NULL) ? 1 : 0;");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#define export_injs() do { ");
      final Function1<String, String> _function_10 = (String i) -> {
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("{ int ival = (int)(rand() % (");
        CharSequence _xifexpression = null;
        boolean _equals = Objects.equal(i, "t");
        if (_equals) {
          StringConcatenation _builder_2 = new StringConcatenation();
          _builder_2.append("T-(2*");
          _builder_2.append(TT);
          _builder_2.append(")");
          _xifexpression = _builder_2;
        } else {
          StringConcatenation _builder_3 = new StringConcatenation();
          _builder_3.append("N-(2*");
          _builder_3.append(TS);
          _builder_3.append(")");
          _xifexpression = _builder_3;
        }
        _builder_1.append(_xifexpression);
        _builder_1.append(") + ");
        Integer _xifexpression_1 = null;
        boolean _equals_1 = Objects.equal(i, "t");
        if (_equals_1) {
          _xifexpression_1 = Integer.valueOf(TT);
        } else {
          _xifexpression_1 = TS;
        }
        _builder_1.append(_xifexpression_1);
        _builder_1.append("); sprintf(val, \"%d\", ival); ");
        _builder_1.append(i);
        _builder_1.append("_INJ = ival; setenv(\"");
        _builder_1.append(i);
        _builder_1.append("_INJ\", val, 1); }");
        return _builder_1.toString();
      };
      String _join_5 = IterableExtensions.join(ListExtensions.<String, String>map(this.getStencilVar().getDomain().getIndexNames(), _function_10), " ");
      _builder.append(_join_5, "\t");
      _builder.append("; } while(0)");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("R = (getenv(\"NUM_RUNS\") != NULL) ? atoi(getenv(\"NUM_RUNS\")) : 100;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("runBox = (int)log10(R) + 1;");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// if THRESHOLD not explicitly set, do short profiling to estimate the");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// noise due to floating point round off errors");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("const char* threshold = getenv(\"THRESHOLD\");");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("float threshold_v1, threshold_v2;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("if (threshold == NULL) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("struct Result result;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("long input_T = T;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("T = ");
      Integer _max = IterableExtensions.<Integer>max(Collections.<Integer>unmodifiableList(CollectionLiterals.<Integer>newArrayList(Integer.valueOf(100), Integer.valueOf((4 * TT)))));
      _builder.append(_max, "\t\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("result = ");
      CharSequence _call_3 = this.call(this.v1System);
      _builder.append(_call_3, "\t\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("printf(\"floating point noise: %E\\n\", result.noise);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("float thresholds[10] = { 1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10 };");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("for (int i=9; i>=0; i--) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("threshold_v1 = thresholds[i];");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if (threshold_v1 > fabs(result.noise))");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("break;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("printf(\" threshold_v1 set to: %E\\n\", threshold_v1);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("result = ");
      CharSequence _call_4 = this.call(this.v2System);
      _builder.append(_call_4, "\t\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t");
      _builder.append("printf(\"floating point noise: %E\\n\", result.noise);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("for (int i=9; i>=0; i--) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("threshold_v2 = thresholds[i];");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("if (threshold_v2 > fabs(result.noise))");
      _builder.newLine();
      _builder.append("\t\t\t\t");
      _builder.append("break;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("printf(\" threshold_v2 set to: %E\\n\", threshold_v2);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("T = input_T;");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("printHeader();");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      final Function1<String, String> _function_11 = (String i) -> {
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("int ");
        _builder_1.append(i);
        _builder_1.append("_INJ");
        return _builder_1.toString();
      };
      String _join_6 = IterableExtensions.join(ListExtensions.<String, String>map(this.getStencilVar().getDomain().getIndexNames(), _function_11), "; \n");
      _builder.append(_join_6, "\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("const char* verbose = getenv(\"VERBOSE\");");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("const char* single_bit = getenv(\"BIT\");");
      _builder.newLine();
      _builder.append("\t");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// ABFTv1");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("char val[50];");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sprintf(val, \"%E\", threshold_v1); ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("setenv(\"THRESHOLD\", val, 1);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("for (int bit=31; bit>=8; bit--) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if (single_bit != NULL && atoi(single_bit) != bit)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("continue;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("char val[50];");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("sprintf(val, \"%d\", bit); ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("setenv(\"bit\", val, 1);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("struct ResultsSummary v_avg = new_result_summary();");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("for (run=0; run<R; run++) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      final Function1<Variable, String> _function_12 = (Variable it) -> {
        return this.inputInitialization(it);
      };
      String _join_7 = IterableExtensions.join(ListExtensions.<Variable, String>map(system.getInputs(), _function_12), "\n");
      _builder.append(_join_7, "\t\t\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("export_injs();");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("struct Result v = ");
      CharSequence _call_5 = this.call(this.v1System);
      _builder.append(_call_5, "\t\t\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("accumulate_result(&v_avg, v);");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("print(1, v);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("print_summary(1, &v_avg);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("// ABFTv2");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("sprintf(val, \"%E\", threshold_v2); ");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("setenv(\"THRESHOLD\", val, 1);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("for (int bit=31; bit>=8; bit--) {");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("if (single_bit != NULL && atoi(single_bit) != bit)");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("continue;");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("char val[50];");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("sprintf(val, \"%d\", bit); ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("setenv(\"bit\", val, 1);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("struct ResultsSummary v_avg = new_result_summary();");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("for (run=0; run<R; run++) {");
      _builder.newLine();
      _builder.append("\t\t\t");
      final Function1<Variable, String> _function_13 = (Variable it) -> {
        return this.inputInitialization(it);
      };
      String _join_8 = IterableExtensions.join(ListExtensions.<Variable, String>map(system.getInputs(), _function_13), "\n");
      _builder.append(_join_8, "\t\t\t");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("export_injs();");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("struct Result v = ");
      CharSequence _call_6 = this.call(this.v2System);
      _builder.append(_call_6, "\t\t\t");
      _builder.append(";");
      _builder.newLineIfNotEmpty();
      _builder.append("\t\t\t");
      _builder.append("accumulate_result(&v_avg, v);");
      _builder.newLine();
      _builder.append("\t\t\t");
      _builder.append("print(2, v);");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("print_summary(2, &v_avg);");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("}");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("#endif");
      _builder.newLine();
      _builder.newLine();
      _builder.append("\t");
      _builder.append("return 0;");
      _builder.newLine();
      _builder.append("}");
      _builder.newLine();
      final String code = _builder.toString();
      _xblockexpression = code;
    }
    return _xblockexpression;
  }

  public String inputInitialization(final Variable variable) {
    String _xblockexpression = null;
    {
      String _stmtPrefix = this.getStmtPrefix();
      String _name = variable.getName();
      final String stmtName = (_stmtPrefix + _name);
      final ISLSet domain = variable.getDomain().copy().setTupleName(stmtName);
      final String indexNameStr = IterableExtensions.join(domain.getIndexNames(), ",");
      final String paramStr = ABFT.buildParamStr(variable);
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("domain: \"");
      String _string = domain.toString();
      _builder.append(_string);
      _builder.append("\"");
      _builder.newLineIfNotEmpty();
      _builder.append("child:");
      _builder.newLine();
      _builder.append("  ");
      _builder.append("schedule: \"");
      _builder.append(paramStr, "  ");
      _builder.append("->[\\");
      _builder.newLineIfNotEmpty();
      _builder.append("    ");
      final Function1<String, String> _function = (String i) -> {
        StringConcatenation _builder_1 = new StringConcatenation();
        _builder_1.append("{ ");
        _builder_1.append(stmtName);
        _builder_1.append("[");
        _builder_1.append(indexNameStr);
        _builder_1.append("]->[");
        _builder_1.append(i);
        _builder_1.append("] }");
        return _builder_1.toString();
      };
      String _join = IterableExtensions.join(ListExtensions.<String, String>map(domain.getIndexNames(), _function), ", \\\n");
      _builder.append(_join, "    ");
      _builder.append(" \\");
      _builder.newLineIfNotEmpty();
      _builder.append("  ");
      _builder.append("]\"");
      _builder.newLine();
      final ISLSchedule initSchedule = ISLUtil.toISLSchedule(_builder);
      final ISLIdentifierList iterators = ISLUtil.toISLIdentifierList(((String[])Conversions.unwrapArray(domain.getIndexNames(), String.class)));
      final ISLASTBuild build = ISLASTBuild.buildFromContext(initSchedule.getDomain().copy().params()).setIterators(iterators.copy());
      final ISLASTNode node = build.generate(initSchedule.copy());
      final ISLASTNodeVisitor codegenVisitor = new ISLASTNodeVisitor().genC(node);
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("// ");
      String _name_1 = variable.getName();
      _builder_1.append(_name_1);
      _builder_1.append(" initialization");
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("#define ");
      _builder_1.append(stmtName);
      _builder_1.append("(");
      _builder_1.append(indexNameStr);
      _builder_1.append(") ");
      String _name_2 = variable.getName();
      _builder_1.append(_name_2);
      _builder_1.append("(");
      _builder_1.append(indexNameStr);
      _builder_1.append(") = rand() % 100 + 1");
      _builder_1.newLineIfNotEmpty();
      String _code = codegenVisitor.toCode();
      _builder_1.append(_code);
      _builder_1.newLineIfNotEmpty();
      _builder_1.append("#undef ");
      _builder_1.append(stmtName);
      _builder_1.newLineIfNotEmpty();
      final String code = _builder_1.toString();
      _xblockexpression = code;
    }
    return _xblockexpression;
  }

  public CharSequence call(final AlphaSystem system) {
    return this.call(system, new String[] {});
  }

  public CharSequence call(final AlphaSystem system, final String[] extraArgs) {
    CharSequence _xblockexpression = null;
    {
      final List<String> paramArgs = system.getParameterDomain().getParamNames();
      EList<Variable> _inputs = system.getInputs();
      EList<Variable> _outputs = system.getOutputs();
      final Function1<Variable, String> _function = (Variable it) -> {
        return it.getName();
      };
      final Iterable<String> ioArgs = IterableExtensions.<Variable, String>map(Iterables.<Variable>concat(_inputs, _outputs), _function);
      StringConcatenation _builder = new StringConcatenation();
      String _name = system.getName();
      _builder.append(_name);
      _builder.append("(");
      Iterable<String> _plus = Iterables.<String>concat(paramArgs, ioArgs);
      String _join = IterableExtensions.join(Iterables.<String>concat(_plus, ((Iterable<? extends String>)Conversions.doWrapArray(extraArgs))), ", ");
      _builder.append(_join);
      _builder.append(")");
      _xblockexpression = _builder;
    }
    return _xblockexpression;
  }

  @Override
  public String localMemoryAllocation() {
    EList<Variable> _inputs = this.getSystem().getInputs();
    EList<Variable> _outputs = this.getSystem().getOutputs();
    return this.memoryAllocation(((Variable[])Conversions.unwrapArray(Iterables.<Variable>concat(_inputs, _outputs), Variable.class)));
  }
}
