/*
 * generated by Xtext 2.27.0
 */
package alpha.targetmapping.scoping;

import alpha.model.scoping.AlphaScopeProvider;

public abstract class AbstractTargetMappingScopeProvider extends AlphaScopeProvider {
}
