/**
 * generated by Xtext 2.15.0
 */
package alpha.commands.model.formatting2;

import alpha.commands.model.services.CommandsGrammarAccess;
import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;

@SuppressWarnings("all")
public class CommandsFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private CommandsGrammarAccess _commandsGrammarAccess;

  protected void _format(final /* AlphaCommandsRoot */Object alphaCommandsRoot, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ncategories cannot be resolved"
      + "\nformat cannot be resolved");
  }

  protected void _format(final /* AlphaCommandCategory */Object alphaCommandCategory, @Extension final IFormattableDocument document) {
    throw new Error("Unresolved compilation problems:"
      + "\ncommands cannot be resolved"
      + "\nformat cannot be resolved");
  }

  public void format(final Object alphaCommandsRoot, final IFormattableDocument document) {
    if (alphaCommandsRoot instanceof XtextResource) {
      _format((XtextResource)alphaCommandsRoot, document);
      return;
    } else if (alphaCommandsRoot instanceof EObject) {
      _format((EObject)alphaCommandsRoot, document);
      return;
    } else if (alphaCommandsRoot == null) {
      _format((Void)null, document);
      return;
    } else if (alphaCommandsRoot != null) {
      _format(alphaCommandsRoot, document);
      return;
    } else if (alphaCommandsRoot != null) {
      _format(alphaCommandsRoot, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(alphaCommandsRoot, document).toString());
    }
  }
}
