name: build

on:
  pull_request:
    branches:
    - main

jobs:

  build-plugin:
    runs-on: maven:3-jdk-11

    steps:
    - uses: actions/checkout@v2

    - name: build alpha
      run: mvn clean package
